- file:
    path: /etc/opt/chrome/policies/managed/
    state: directory
    mode: 0755

- name: Setting Chrome Group Policies
  copy: src=../files/policy.json dest=/etc/opt/chrome/policies/managed/policy.json owner=root group=root mode=0644

- name: Remove Blacklisted Packages
  apt: pkg={{ item  }} state=absent
  with_items:
  - chromium-browser

- cron:
    name: "kill firefox"
    minute: "*/5"
    job: "killall firefox >/dev/null 2>&1"
